export const LATENCY = 1000;

export const PAGINATION_CONFIG = {
    itemsPerPage: 10,
    currentPage: 1,
    totalItems: 0
};

export const PAGINATION_CONFIG_FOR_TABLE = {
    itemsPerPage: 10,
    currentPage: 1,
    totalItems: 0,
    pageSizeOptions: [5, 10, 25, 50, 100]
};

export const REG_EX = {
    user_id: /^[0-9\sA-Za-z\u00C0-\u00FF\~\#\";\/!@$%^&*()_\+\{\}\?\-\[\]\\,.\u0152\u0153\u20A0\u20A3\u0178\u20AC\u2013\u2014\u00C6\u00E6\u00C4\u00E4\u20A3]{5,32}$/,
    password: /^[^|]{6,32}$/,
    email: /^(?!.*([.])\1{1})([\w\.\-\+\<\>\{\}\=\`\|\?]+)@(?![.-])([a-zA-Z\d.-]+)\.([a-zA-Z.][a-zA-Z]{1,6})$/,
    create_user_id: /^[0-9\sA-Za-z\!@$%^*()_\+\{\}\?\-\[\]\\,.]{5,32}$/,
    four_consecutive_digits: /\d{4}/,
    create_password: /^(?=(?:.*?[0-9]){2})(?=.*[a-zA-Z])[0-9\sA-Za-z\!@\#$%^&*()_\+\{\}?\-\[\]\\,.]{6,32}$/,
    strong_password: /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,}$/,
    checkpoint_response: /^[0-9\sA-Za-z\?\#,.:;\\<|>!=@\#$%^*_\-\+\{\}\[\]]{1,}$/,
    formatted_date: /^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$/,
    formatted_date_with_stars_pattern: /^(0[1-9]|1[012]|\*\*)[- /.](0[1-9]|[12][0-9]|3[01]|\*\*)[- /.](((19|20)\d\d)|(\*\*\*\*))$/,
    cvv: /^\d{3,4}$/,
    last_four_digits: /^\d{4}$/,
    card_number_length: /^.{9,16}$/,
    card_number_format: /^[0-9]*$/,
    card_name: /^[a-zA-Z\s\-'\.]{4,30}$/,
    aba_routing: /^\d{1,9}$/,
    account_number: /^\d{1,17}$/,
    currency: /^\d{1,10}(\.\d{0,2})?$|^\.\d{1,2}$/,
    nickname: /^[\s\dA-Za-z\u00C0-\u00FF\!@\#$%^&\*\(\)_\+\{\}\?\-\=\[\]\,\.\u0152\u0153\u20A0\u20A3\u0178\u20AC\u00C6\u00E6\u00C4\u00E4\u20A3]{0,30}$/,
    card_nickname: /^[\s\dA-Za-z\u00C0-\u00FF\!@\#$%^&\*\(\)_\+\{\}\?\-\[\]\,\~\\\\|\/u0152\u0153\u20A0\u20A3\u0178\u20AC\u00C6\u00E6\u00C4\u00E4\u20A3]{0,30}$/,
    three_repeating_characters: /(.)\1{2,}/,
    phone_number_US: /^\d{10}$/,
    has_a_number: /\d/,
    security_question_format: /^[0-9\sA-Za-z\u00C0-\u00FF0-9\u0152\u0153\u20A0\u0178\u20A3\u20AC\<\>\!@\#$%^*_\+\{\}|:\?\-\=\[\]\\;/.]*$/,
    whole_number: /^([1-9][0-9]*)$/,
    name: /^[A-Za-z\.\-\'\s,]*$/,
    name_with_latin_characters: /^[A-Za-z\.\-\'\s,\u00C0-\u00FF\u0152\u0153\u20A0\u20A3\u0178\u20AC\u00C6\u00E6\u00C4\u00E4\u20A3]*$/,
    numeric_only: /^[0-9]*$/,
    numeric_only_with_spaces: /^[0-9\s]*$/,
    numeric_two_decimal_places: /^\d+(\.\d{1,2})?$/,
    alpha_only: /^[A-Za-z]*$/,
    alpha_upper: /^[A-Z]*$/,
    alpha_lower: /^[a-z]*$/,
    is_special_char: /^[a-zA-Z0-9!@#\$%\^\&*\)\(+=._-]+$/,
    alpha_with_spaces: /^[A-Za-z\s]*$/,
    alpha_numeric_only: /^[0-9A-Za-z]*$/,
    alphanumeric_with_spaces: /^[A-Za-z0-9\s]*$/,
    balance_transfer_city: /^[A-Za-z\u00C0-\u00FF\u0152\u0153\u20A0\u20A3\u0178\u20AC\u00C6\u00E6\u00C4\u00E4\u20A3\s\.]{1,18}$/,
    zipcode: /^[0-9]{5,5}$/,
    postal_code: /^[A-Za-z][0-9][A-Za-z]\s[0-9][A-Za-z][0-9]$/,
    consecutive_spaces: /\s\s/,
    leading_or_trailing_spaces: /^[\s]+|[\s]+$/,
    activation_code: /^[A-Za-z0-9]{8}$/,
    dispute_charge_text: /^[^<>\"%]*$/,
    message_subject: /^[^=\"'<>]*$/,
    message_body: /^[^=\"'<>]*$/,
    pan_number: /^[A-Za-z]{5}\d{4}[A-Za-z]{1}$/,
    alphanumericWithSpaceAllowedChars: /^[A-Za-z0-9\.\-\'\s,&()]*$/,
    onlyspace: /^\s*$/,
    alphanumericWithoutSpace: /^[a-zA-Z0-9]*$/
};

export const LANGUAGE_LIST = [
    { code: 'en_US', label: 'EN', ISOLangName: 'English', endonym: 'English' },
    { code: 'es_US', label: 'ES', ISOLangName: 'Spanish', endonym: 'Español' },
    { code: 'bn_IN', label: 'BN', ISOLangName: 'Bengali', endonym: 'Bangla' }
];

export const USER_STATUS: any = {
    'Y': 'Active',
    'N': 'Inactive',
    'D': 'Deleted',
    'B': 'Blocked'
};

export const ADDRESS_TYPES: any = {
    'C': 'Present',
    'P': 'Permanent',
    'W': 'Work',
    'H': 'Permanent'
};

export const APP_ICONS: any = {
  'home': { mat: 'home', prime: 'pi pi-home', bs: 'bi bi-house' },
  'dashboard': { mat: 'speed', prime: 'pi pi-home', bs: 'bi bi-speedometer' },
  'user': { mat: 'account_circle', prime: 'pi pi-user', bs: 'bi bi-person-circle' },
  'users': { mat: 'people', prime: 'pi pi-users', bs: 'bi bi-people' },
  'add': { mat: 'add', prime: 'pi pi-plus', bs: 'bi bi-plus-lg' },
  'edit': { mat: 'edit', prime: 'pi pi-pencil', bs: 'bi bi-pencil' },
  'userEdit': { mat: 'edit', prime: 'pi pi-user-edit', bs: 'bi bi-person-gear' },
  'delete': { mat: 'delete', prime: 'pi pi-trash', bs: 'bi bi-trash' },
  'info': { mat: 'info', prime: 'pi pi-info-circle', bs: 'bi bi-info-circle' },
  'success': { mat: 'check_circle', prime: 'pi pi-check-circle', bs: 'bi bi-check-circle' },
  'error': { mat: 'error_outline', prime: 'pi pi-exclamation-circle', bs: 'bi bi-exclamation-circle' },
  'warning': { mat: 'warning_amber', prime: 'pi pi-exclamation-triangle', bs: 'bi bi-exclamation-triangle' },
  'admin': { mat: 'admin_panel_settings', prime: 'pi pi-lock', bs: 'bi bi-person-lock' },
  'selfService': { mat: 'fingerprint', prime: 'pi pi-folder', bs: 'bi bi-fingerprint' },
  'chevronLeft': { mat: 'chevron_left', prime: 'pi pi-angle-left', bs: 'bi bi-chevron-left' },
  'angleUp': { mat: 'expand_less', prime: 'pi pi-angle-up', bs: 'bi bi-chevron-up' },
  'angleDown': { mat: 'expand_more', prime: 'pi pi-angle-up', bs: 'bi bi-chevron-up' },
  'chevronRight': { mat: 'chevron_right', prime: 'pi pi-angle-right', bs: 'bi bi-chevron-right' },
  'arrowRight': { mat: 'arrow_right_alt', prime: 'pi pi-arrow-right', bs: 'bi bi-arrow-right-short' },
  'currency': { mat: 'paid', prime: 'pi pi-dollar', bs: 'bi bi-currency-dollar' },
  'clock': { mat: 'watch_later', prime: 'pi pi-clock', bs: 'bi bi-clock' },
  'globe': { mat: 'language', prime: 'pi pi-globe', bs: 'bi bi-globe' },
  'map': { mat: 'place', prime: 'pi pi-map-marker', bs: 'bi bi-geo-alt' },
  'phone': { mat: 'phone', prime: 'pi pi-phone', bs: 'bi bi-telephone' },
  'email': { mat: 'email', prime: 'pi pi-envelope', bs: 'bi bi-envelope' },
  'sun': { mat: 'light_mode', prime: 'pi pi-sun', bs: 'bi bi-brightness-high' },
  'moon': { mat: 'dark_mode', prime: 'pi pi-moon', bs: 'bi bi-moon-stars' },
  'circle': { mat: 'trip_origin', prime: 'pi pi-circle-fill', bs: 'bi bi-circle-fill' },
  'signout': { mat: 'logout', prime: 'pi pi-sign-out', bs: 'bi bi-box-arrow-right' },
  'notification': { mat: 'notifications', prime: 'pi pi-bell', bs: 'bi bi-app-indicator' },
  'linechart': { mat: 'analytics', prime: 'pi pi-chart-line', bs: 'bi bi-bar-chart-line' },
  'qualification': { mat: 'school', prime: 'pi pi-book', bs: 'bi bi-mortarboard' },
  'job': { mat: 'work_history', prime: 'pi pi-briefcase', bs: 'bi bi-briefcase' },
  'heart': { mat: 'medical_services', prime: 'pi pi-heart', bs: 'bi bi-heart' },
  'actionRequired': { mat: 'help_outline', prime: 'pi pi-question-circle', bs: 'bi bi-question-circle' },
  'check': { mat: 'check_circle', prime: 'pi pi-check-circle', bs: 'bi bi-check-circle' },
  'cross': { mat: 'cancel', prime: 'pi pi-times-circle', bs: 'bi bi-x-circle' },
  'close': { mat: 'close', prime: 'pi pi-times', bs: 'bi bi-x' },
  'question': { mat: 'help_outline', prime: 'pi pi-question-circle', bs: 'bi bi-question-circle' },
  'send': { mat: 'send', prime: 'pi pi-send', bs: 'bi bi-send-check' },
  'calendar': { mat: 'calendar_month', prime: 'pi pi-calendar', bs: 'bi bi-calendar-check' },
  'tasks': { mat: 'task', prime: 'pi pi-th-large', bs: 'bi bi-columns-gap' },
  'search': { mat: 'search', prime: 'pi pi-search', bs: 'bi bi-search' },
  'settings': { mat: 'settings', prime: 'pi pi-cog', bs: 'bi bi-gear' },
  'upload': { mat: 'file_upload', prime: 'pi pi-upload', bs: 'bi bi-upload' },
  'download': { mat: 'file_download', prime: 'pi pi-download', bs: 'bi bi-download' },
  'exportxls': { mat: 'file_download', prime: 'pi pi-file-excel', bs: 'bi bi-file-earmark-excel' },
  'exportpdf': { mat: 'picture_as_pdf', prime: 'pi pi-file-pdf', bs: 'bi bi-filetype-pdf' },
  'menu': { mat: 'menu', prime: 'pi pi-bars', bs: 'bi bi-list' },
  'comment': { mat: 'comment', prime: 'pi pi-comment', bs: 'bi bi-comment' },
  'verified': { mat: 'verified', prime: 'pi pi-verified', bs: 'bi bi-verified' },
  'projects': { mat: 'list_alt', prime: 'pi pi-info', bs: 'bi bi-info' },
  'calendarclock': { mat: 'calendar_clock', prime: 'pi pi-info', bs: 'bi bi-info' },
  'pendingaction': { mat: 'pending_actions', prime: 'pi pi-info', bs: 'bi bi-info' },
  'username': { mat: 'person', prime: 'pi pi-info', bs: 'bi bi-info' },
  'password': { mat: 'password', prime: 'pi pi-info', bs: 'bi bi-info' },
  'language': { mat: 'language', prime: 'pi pi-globe', bs: 'bi bi-globe' },
  'note': { mat: 'note_stack', prime: 'pi pi-note', bs: 'bi bi-note' },
  'report': { mat: 'report', prime: 'pi pi-report', bs: 'bi bi-report' },
  'leave': { mat: 'beach_access', prime: 'pi pi-travel', bs: 'bi bi-travel' },
  'timesheet': { mat: 'more_time', prime: 'pi pi-travel', bs: 'bi bi-travel' },
  'datacheck': { mat: 'data_check', prime: 'pi pi-travel', bs: 'bi bi-travel' },
  'history': { mat: 'history', prime: 'pi pi-travel', bs: 'bi bi-travel' },
  'history2': { mat: 'history_2', prime: 'pi pi-travel', bs: 'bi bi-travel' },
  'diversity': { mat: 'diversity_1', prime: 'pi pi-travel', bs: 'bi bi-travel' },
};